//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<double> Temperature { get; set; }
    }
}
